Force an instance shutdown on cloud-init error (#68)
* Force an instance shutdown on cloud-init error

* Run shellcheck on user data scripts

diff --git a/cloudformation/main.yaml b/cloudformation/main.yaml
--- a/cloudformation/main.yaml
+++ b/cloudformation/main.yaml
@@ -197,6 +197,13 @@ Resources:
               set -e
               set -o pipefail
 
+              fatal_error () {
+                printf "FATAL ERROR: shutting down\n"
+                shutdown -h now
+              }
+
+              trap 'fatal_error' ERR
+
               # Enable the nbd module
               modprobe nbd nbds_max=128
               echo "nbd" > /etc/modules-load.d/nbd.conf
@@ -223,26 +230,26 @@ Resources:
                   --header "X-Amz-Security-Token: $AWS_SECURITY_TOKEN" \
                   --header "X-Amz-Target: secretsmanager.GetSecretValue" \
                   --header "Content-Type: application/x-amz-json-1.1" \
-                  --data '{"SecretId": "${SecretAPIKeyArn}"}')
+                  --data "{\"SecretId\": \"${SecretAPIKeyArn}\"}")
 
               DD_HOSTNAME="agentless-scanning-$IMDS_AWS_REGION-$IMDS_INSTANCE_ID"
               DD_SITE="${DatadogSite}"
               DD_API_KEY="$(jq -r '.SecretString' <<< "$AWS_SECRET_JSON")"
+              DD_AGENT_MINOR_VERSION="50.3"
+              DD_SCANNER_VERSION="7.51.0~agentless~scanner~2024022201"
 
               hostnamectl hostname $DD_HOSTNAME
 
-              echo $DD_HOSTNAME > /etc/hostname
               # Install the agent
               DD_API_KEY=$DD_API_KEY \
                 DD_SITE="$DD_SITE" \
-                DD_HOSTNAME=$DD_HOSTNAME \
-                DD_AGENT_MINOR_VERSION="50.3" \
+                DD_HOSTNAME="$DD_HOSTNAME" \
+                DD_AGENT_MINOR_VERSION="$DD_AGENT_MINOR_VERSION" \
                 bash -c "$(curl -L https://s3.amazonaws.com/dd-agent/scripts/install_script_agent7.sh)"
 
               # Install the agentless-scanner
-              SCANNER_VERSION="7.51.0~agentless~scanner~2024022201"
-              curl -sL -o /tmp/datadog-agentless-scanner_$SCANNER_VERSION-1_arm64.deb https://s3.amazonaws.com/apt.datad0g.com/pool/d/da/datadog-agentless-scanner_$SCANNER_VERSION-1_arm64.deb
-              dpkg -i /tmp/datadog-agentless-scanner_$SCANNER_VERSION-1_arm64.deb
+              curl -sL -o "/tmp/datadog-agentless-scanner_$DD_SCANNER_VERSION-1_arm64.deb" "https://s3.amazonaws.com/apt.datad0g.com/pool/d/da/datadog-agentless-scanner_$DD_SCANNER_VERSION-1_arm64.deb"
+              dpkg -i "/tmp/datadog-agentless-scanner_$DD_SCANNER_VERSION-1_arm64.deb"
 
               # Patch agent configuration
               sed -i '/.*logs_enabled:.*/a logs_enabled: true'           /etc/datadog-agent/datadog.yaml
